#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.9.{build}.0
install:
    - git clone https://github.com/PlagueHO/DscResource.Tests

    - ps: |
        $moduleName = 'xStorage'
        $mainModuleFolder = "Modules\$moduleName"
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask `
            -PesterMaximumVersion 3.4.6

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Harness' `
            -MainModulePath $mainModuleFolder
#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -MainModulePath $mainModuleFolder `
            -ResourceModuleName $moduleName
